---
title: Bluer's Notes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@bluer.com
description: 'A notes archive

'
baseurl: ''
url: http://notes.bluer.com
twitter_username: kevinbluer
github_username: kevinbluer
markdown: kramdown
